### ISSUE TITLE
node・npm のバージョンがしりたいです

### ISSUE THREAD

**Issue by kidapu** [dot-by-dot-inc/dotby.jp-2015#4]
@Saqoosha さん

このレポジトリに対して以下の操作すると。

```
$ git clone https://github.com/dot-by-dot-inc/dotby.jp-2015.git
$ npm install
$ npm run start 
```

こんなエラーがでました。

```
$ node_modules/grunt-cli/bin/grunt                             


#
# Fatal error in , line 0
# Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
#
#
#
#FailureMessage Object: 0x7ffeefbfb7c0fish: 'node_modules/grunt-cli/bin/grunt' terminated by signal SIGILL (Illegal instruction)
```

そのままエラーでぐぐると、[このあたりの人が](https://github.com/nodejs/node/issues/10659#issuecomment-270927364
)、「関連する npm module のバージョンをとにかく最新にしたら動くぞ」といっていたので、その通りやったら、エラーが変わったのですが。

coffee script が 1 系から 2 系にアップデートされちゃって、関係ない script をなおしていかないといけない感じになったので、つらいと思い。

開発環境を合わせたく、Saqoosha さんが作業されている node・ npm、 あとできれば mac os のバージョンを教えて頂けると嬉しいです。（ちなみに、ぼくは HighSierraです。）

**Comment by Saqoosha** [comment]
@kidapu 2015 年のプロジェクトなので最新版だといろいろアレですね。。

node v4.4.3 だと正常にビルドできてるので、それがいんじゃないでしょか。わたしは https://github.com/hokaccha/nodebrew で `nodebrew install-binary v4.4.3` して `nodebrew use v4.4.3` して `npm i` でいけている気がします。

**Comment by Saqoosha** [comment]
```
⟫ node --version
v4.4.3
⟫ npm --version
2.15.1
```

**Comment by Saqoosha** [comment]
```
⟫ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77
```

**Comment by kidapu** [comment]
@Saqoosha 
node のバージョン合わせたらビルドできました！ありがとうございます！
